### PR TITLE
Add cross-compile release workflow.

### PR DESCRIPTION
**Pull request by mrstegeman**
When you push a new tag named `vX.Y.Z`, this will automatically
cross-compile the add-on for all of the supported platforms. This
will allow the release to be handled automatically, rather than
building things manually via WebThingsIO/addon-builder.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Thanks for merging! Would you mind building a new release? I’m trying to get all add-on packages off of S3 and hosted by the individual GitHub repos before Mozilla cuts off our S3 access.

1. Do anything else you want/need to do for this release.
2. Update the version in both `package.json` and `manifest.json`.
3. Tag and push vX.Y.Z.
4. Either let me know or update the appropriate entry in the WebThingsIO/addon-list repo and open a PR.

**Comment by bromagosa** [comment]
Hi Michael,

sorry about the delay. I've been off for a few days and then catching up with things.

Here's the release: https://github.com/bromagosa/microblocks-adapter/releases/tag/v0.5.4

Thanks! :)

**Comment by mrstegeman** [comment]
No problem. It looks like the workflow didn't run, which has been happening once in awhile. #26 will fix that. You'll have to merge and then build another new release.

**Comment by bromagosa** [comment]
Thank you, here's the new release: https://github.com/bromagosa/microblocks-adapter/releases/tag/v0.5.5

**Pull request merged**
